USERNAME="eS4mR71Tltz0POlJ"			#Put here your autogenerated username
PASSWORD="F907Kup79ymcd8Qr"			#Put here your autogenerated password
HOSTNAME="your-dyndns.your-domain.tld"	#Put here your Dynamic DNS

IP=$(curl -s "https://api64.ipify.org/")	#Resolves your current public IP

URL="https://${USERNAME}:${PASSWORD}@domains.google.com/nic/update?hostname=${HOSTNAME}&myip=${IP}"
curl -s $URL					#Updates Google DNS Record
